### ISSUE TITLE
Define where README.md is displayed on directory listing

### ISSUE THREAD

**Issue by hugo-akaora** [9001/copyparty#105]
Hello @9001,

Would be great to define where `README.md` is displayed : before or after directory content.

Current behavior is neat as it's the same than Github/Gitlab, but for example Nextcloud displays it before directory listing.

I think I won't have to use `.prologue.html` or `.epilogue.html` if I can tweak it globally, per volume or directory. I prefer markdown than html because it's easier to use for end users.

Thank you so much!

**Comment by 9001** [comment]
Good idea :>

A global and/or per-volume option should be easy enough, but I'm thinking about how we could do per-directory, since that might be very useful in some cases.

One approach would be to leave README.md alone so it continues behaving like it does currently, but there could also be PREADME.md which appears before the directory listing. That way, you could have both a readme and a preadme in the same folder.

Alternatively, it could be a hint that you specify inside the README, maybe something like `<!-- copyparty:show_above -->` would make it appear at the top.

I think I like the PREADME idea more, but I'll take a look how tricky it would be to code before I say for sure :+1:

**Comment by 9001** [comment]
alright, `preadme.md` / `PREADME.md` will be displayed at the top of the file listing as of the next version, which will be released either tonight or tomorrow.

one thing I'd like to mention is that preadme/prologue has the disadvantage that it causes flickering when changing directories; this is due to the security sandbox that is default-enabled.

if your copyparty server is configured to only allow uploads from people you trust, then you can disable the sandbox with `--no-sb-lg` and `--no-sb-md` for a smoother experience. But please only do this if you are certain that malicious files can never appear on your server.
