### ISSUE TITLE
Web interface not accessible at "hostname.local"

### ISSUE THREAD

**Issue by dshemnv** [9001/copyparty#106]
**Describe the bug**
Not sure if a bug or I misunderstood the documentation. When launching copyparty with `-z` and trying to access the web interface using "http://myhostname.local", the browser says it is unreachable.

**To Reproduce**
- Run copyparty with the `-z` flag:
```shell
$ hostname
$ home
$ copyparty -v /home/me/mystuff:/stuff:rw -z
```
- Open "http://home.local" in Firefox
- Get a "Unable to connect" error

**Expected behavior**
Get access to the web interface on "http://home.local".

**Server details**
if the issue is possibly on the server-side, then mention some of the following:
* server OS / version:  Arch
* python version: 3.12.6
* copyparty arguments: -v /home/me/mystuff:/stuff:rw -z
* filesystem (`lsblk -f` on linux): btrfs

**Client details**
Same. But also tried to access from another machine running Ubuntu 20.04

**Additional context**
Zeroconf is configured correctly on my machine, as explained on the Arch Wiki.

**Comment by 9001** [comment]
hey, thanks for trying copyparty :>

the issue is that the server listens on port 3923 by default, while browsers expect either 80 (for http) or 443 (for https). I've probably not communicated this very well for the zeroconf option.

3923 is the default because both Linux and Macos prevent you from using ports below 1024 due to security reasons.

I think you have five options, roughly sorted from best to worst:

* `option 1:` access the server with http://myhostname.local:3923/ to keep using the default port
  * this is the safest/easiest option, just kinda sucks
  * but if you also enable `--qr` to generate a QR-code with the link on startup, then the QR-code will include the correct port

* `option 2:` forward port 80 and 443 to port 3923
  * this is still perfectly safe, just cumbersome since you'll need to do this after every reboot:
    ```bash
    iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 3923
    iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 3923
    ```

* `option 3:` allow the use of ports 80 and 443, and then use those instead
  * note that this will [weaken your security](https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html) by a tiny bit, since all python scripts are then technically able to pretend they are a privileged service -- however I wouldn't be too concerned about this on an average workstation, especially if you already have a dns server running (like dnsmasq)
  * on Linux, first do this:
    ```bash
    setcap CAP_NET_BIND_SERVICE=+eip $(realpath $(which python))
    ```
  * then add `-p 80,443` to the copyparty arguments

* `option 4:` set up a [reverse-proxy](https://github.com/9001/copyparty#reverse-proxy) on port 80/443 and relay to copyparty
  * this is the option that makes the most sense on proper headless servers, but it sounds like you're running this on a workstation, in which case that would just be overkill 

* `option 5:` run copyparty as root (please don't), and also add `-p 80,443` to the args

i'll get this added to the documentation somehow, thanks for the headsup :>
