### ISSUE TITLE
generate rss feed from media in directory

### ISSUE THREAD

**Issue by hugo-akaora** [9001/copyparty#109]
Hello @9001, I hope you're okay?

I can accross that project today: https://github.com/amsehili/genRSS ; and thought maybe it / or a similar feature, could be "easily" integrated in copyparty.

That way, people with podcasts app (eg: the excellent AntennaPod) should download media directly using RSS feed.

It would be very handy!

Thank you!

**Comment by 9001** [comment]
yo, that's a really cool idea! I'll give it a go 😁👍 

~~might take a bit though, dayjob's been really busy lately :>~~

EDIT: turns out that was much easier than I anticipated hehe

I'm fairly certain that the code is safe, and it seems to work well with AntennaPod (you were right, this app is fantastic) -- but I wouldn't be surprised if other RSS clients might find something about the output to complain about :p
