### ISSUE TITLE
Implement lazy loading for large directories

### ISSUE THREAD

**Issue by icxes** [9001/copyparty#11]
Sorry, I don't know if lazy loading is the right term but I'm sure you get it

**is your feature request related to a problem? Please describe.**
It takes a long time (up to or more than 5 seconds, and that's not including loading the thumbnails) to load a directory with over 10000 items (at least when using the grid)

**Describe the idea / solution you'd like**
Add an option to load a few hundred/thousand/user-defined amount of items at a time instead

**Describe any alternatives you've considered**
Deleting unnecessary files (unacceptable)

**Additional context**
Search would ideally still work on all items and splitting the items into pages would be a poor idea

**Comment by 9001** [comment]
thanks, was afraid someone would bring that up w

i think the thing you had in mind is called windowing or "virtual tables", and apparently there's a whole bunch of libraries to choose from, just that most of them assume you're using react/vue/something-else-fancy, and there's the drawback that they all have to reimplement CTRL-F since they steal the browser's job of knowing the list items

as for why it's slow in the first place -- for 10k files on...

* firefox: 200ms to process json, 180ms write table dom, 210ms for the navpane, 130ms making the playlist, 440ms in loadgrid (thumbs), and finally 770ms browser rendering = 1.9sec

* chrome: 20ms json, 200ms table, 65ms set_style (unreasonable), 110ms navpane, 20ms set_style again, 40ms playlist, 920ms loadgrid, and 840ms rendering = 2.2sec

so out of 2.2sec, about 0.4s (20%) is from spaghetti such as making the table even tho grid is enabled, always making the playlist ahead of time, dom queries rather than mvc... but that still leaves 1.8sec which would need windowing to be reduced much

don't think proper windowing will be feasible to pull off without a massive overhaul, but only loading the first N items sounds great actually -- render the first ~1000 table/thumbnail items and dump the remaining stuff as hidden plaintext at the bottom of the page (so CTRL-F still works), and then if you scroll to the bottom it'll just do a full repaint of the page to render all the files. Not perfect but should be a big improvement until the fabled preact/something rewrite :>

would probably interrupt audio playback but should be easy to retain+restore any file selection at least

actually, would it be better if it automatically did a reload with the full listing when you scroll down, or should there be buttons down there, like "load 1000 more", "load all"? ...or maybe that should be configurable? both actions would do a full repaint btw, so would become slower each time you hit the "load N more" btn

**Comment by icxes** [comment]
Either "load all" or "load x more" would work for me at least, since usually I'm interested in either 1. some of the first files that show up in huge directories (sorted by date) or 2. the subdirectories of the huge directory. But I imagine if someone is actually interested in seeing more than 1000, they probably don't mind waiting a few seconds to display all of the files? So if I had to choose, I'd guess "load all" is better.

**Comment by 9001** [comment]
aight, ended up with this:
* defaults to showing the first 250 files according to sort prefs
* defaults to loading 4x the amount of files currently shown every time you scroll down
* ctrl-f should work for all files, including metadata values
* cut/paste-selection survives loading additional files, audio playback doesn't
* currently no way to change the defaults through commandline args, figured the defaults were sane enough

lmk if something's off o/
