### ISSUE TITLE
Uncaught ReferenceError: readme is not defined

### ISSUE THREAD

**Issue by SerenoV7** [9001/copyparty#112]
**Describe the bug**
I get the hit a bug screen whenever I try to load into copyparty, logged in and not

**To Reproduce**
idk all I did was update from an older version

**Expected behavior**
no error screen

**Screenshots**
![{C6351F47-D511-4F0E-AAFA-9B382900BDE9}](https://github.com/user-attachments/assets/a0431b46-5138-4a7f-903a-5c8d75c9c7a8)

**Server details**
if the issue is possibly on the server-side, then mention some of the following:
* server OS / version: Ubuntu 22.04.5 LTS
* python version: 3.10.12
* copyparty arguments: -p 3923 -config
* filesystem (`lsblk -f` on linux):  zfs

**Client details**
if the issue is possibly on the client-side, then mention some of the following:
* the device type and model: 
* OS version: Windows 11
* browser version: Cromite Version 130.0.6723.67

**Comment by 9001** [comment]
i think you have an old version of the javascript in your browser cache, could you try pressing CTRL-SHIFT-R and see if that fixes it?

it was supposed to be smart enough to do that automatically, so not sure why it didn't... oh well

**Comment by SerenoV7** [comment]
tried both  CTRL SHIFT R and CTRL F5, neither worked

also tried clearing local and session storage and cookies

**Comment by 9001** [comment]
huh, and the error is still `browser.js @7962:1` like in the screenshot?

**Comment by SerenoV7** [comment]
yep

**Comment by SerenoV7** [comment]
![{C8DDF357-4D11-44C8-9620-761B42BFA277}](https://github.com/user-attachments/assets/4d3b4dda-c349-4531-872b-ac2bc63ab6cd)
Instance link is [https://drive.sereno.one/](https://drive.sereno.one/ )

**Comment by 9001** [comment]
That link works for me, and line 7962 is not at all related to anything readme... could you try another browser? I still suspect this is somehow caching related, perhaps due to bunnycdn?

**Comment by SerenoV7** [comment]
happens on firefox too, same line

**Comment by SerenoV7** [comment]
copyparty was working fine before this update

**Comment by 9001** [comment]
could you save and attach this file? https://drive.sereno.one/.cpr/browser.js?_=GgAN

the reason i'm asking is because I believe you are not getting the same version of this file when the web-ui accesses that link. I believe this is broken caching in bunnycdn.

here's what I'm getting: [browser-sereno-norway.js.zip](https://github.com/user-attachments/files/17504442/browser-sereno-norway.js.zip)

**Comment by SerenoV7** [comment]
[browser.js.zip](https://github.com/user-attachments/files/17504525/browser.js.zip)
here it is

**Comment by 9001** [comment]
yup, this is related to bunnycdn or another intermediate cache/CDN. When you accessed the link directly, you received the correct/current version of the javascript, but when it is loaded by the web-app then a stale copy is loaded (it looks like v1.13.4).

The behavior difference is due to the headers that gets sent from the browser along with the request; the offending caching proxy (maybe bunnycdn?) conditionally returns the stale copy depending on the headers you're sending. So the next step is to try clearing the cache of all intermediate proxies, and figure out which one is not behaving correctly.

**Comment by SerenoV7** [comment]
Cleared BunnyCDN's cache and now it works, thanks sorry for wasting your time 🙏

**Comment by 9001** [comment]
no problem :grin: :+1:  thanks for trying copyparty!
