### ISSUE TITLE
DB constantly rescans / requeues same files for scanning

### ISSUE THREAD

**Issue by mrpops2ko** [9001/copyparty#117]
**Describe the bug**
its my understanding that the usage of the sqlite db is to index the files initially and then to then use that database on startup each time, correct? 

what i've observed happening now, and i'm not sure why - i suspect it might be due to various alt code characters, is that on startup it will rescan files and seemingly never fully commit them to the db, because they start to scan again on startup 

**To Reproduce**
run program > check logs > see generally the files being scanned

if you have some private mail i can attach some logs of it happening

**Expected behavior**
to commit it to the db and not scan again on startup, unless the data has been modified / the files don't exist

**Server details**
i'm using the docker compose version with
`    user: "1000:1000"  # should match the user/group of your fileshare volumes`
perms look good, its not an issue with those i dont think

```
root@alexandria:/mnt/dkr/appdata# cd cpp/
root@alexandria:/mnt/dkr/appdata/cpp# ls -al
total 8
drwxr-xr-x   4 root          root    27 May 20 07:07 ./
drwxrwxrwx 126 nobody        users 4096 Nov 12 15:23 ../
drwxr-xr-x   3 administrator  1000   42 Aug 19 12:05 cpp/
drwxr-xr-x   4 administrator  1000   24 Aug 19 11:57 db/
root@alexandria:/mnt/dkr/appdata/cpp# cd db
root@alexandria:/mnt/dkr/appdata/cpp/db# ls -al
total 0
drwxr-xr-x 4 administrator 1000 24 Aug 19 11:57 ./
drwxr-xr-x 4 root          root 27 May 20 07:07 ../
drwxr-xr-x 4 administrator 1000 96 Nov 12 18:07 o/
drwxr-xr-x 2 administrator 1000 23 Aug 19 11:57 z/
root@alexandria:/mnt/dkr/appdata/cpp# id 1000
uid=1000(administrator) gid=100(users) groups=100(users)
```

hmm this part could be the culprit, will it cause any issues to change from the 1000:1000 user to something mapped on my system? 

i'm not sure this is the problem though because in such an event then nothing would save would it? 

```
root@alexandria:/mnt/dkr/appdata/cpp/db/o# ls -al
total 3227828
drwxr-xr-x 4 administrator 1000         96 Nov 12 18:07 ./
drwxr-xr-x 4 administrator 1000         24 Aug 19 11:57 ../
drwxr-xr-x 2 administrator 1000          6 Sep 17 04:09 ac/
-rw-r--r-- 1 administrator 1000          2 May 20 07:18 owner.txt
drwxr-xr-x 2 administrator 1000          6 Nov  9 18:27 th/
-rw-r--r-- 1 administrator 1000 3304734720 Nov 11 15:17 up2k.db
-rw-r--r-- 1 administrator 1000      32768 Nov 12 18:20 up2k.db-shm
-rw-r--r-- 1 administrator 1000     333752 Nov 12 18:20 up2k.db-wal
root@alexandria:/mnt/dkr/appdata/cpp/cpp# ls -al
total 4
drwxr-xr-x 3 administrator 1000  42 Aug 19 12:05 ./
drwxr-xr-x 4 root          root  27 May 20 07:07 ../
-rwxrwxrwx 1 administrator 1000 635 Aug 19 16:07 config.conf*
drwxr-xr-x 2 administrator 1000 110 Nov  2 13:16 copyparty/
root@alexandria:/mnt/dkr/appdata/cpp/cpp# cat config.conf
# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:

# append some arguments to the commandline;
# accepts anything listed in --help (leading dashes are optional)
# and inline comments are OK if there is 2 spaces before the '#'
[global]
  p: 8086, 3939  # listen on ports 8086 and 3939
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # and enable multimedia indexing
#  idp-h-usr: x-authentik-username
#  idp-h-grp: x-authentik-groups
  shr=/share/
  hist=/db
  ban-404: no
  ban-403: no
  ban-422: no
  ban-url: no
  ban-pw: no
  ihead: *
```
from the documentation 
```
-e2ts also scans for tags in all files that don't have tags yet
-e2dsa also scans all mounted volumes (including readonly ones)
```
what i've noticed is that on boot it doesn't seem like the same files are scanned in the same order, could it be related to the e2ts and the absense of tags? (tags im assuming in this instance refers to music metadata?)

also whats a little frustrating about this too is that theres no graceful stopping of the container in both docker compose and docker whilst the db scan is running

i've read through the front page and searched through the open and closed issues to see if anybody reported anything similar to me but i can't seem to find anything

**Comment by mrpops2ko** [comment]
ok digging into this some more it might be some perm issues with certain files, i've noticed some permission denied issues and when checking out the files they were

```
drwxrwxrwx 1 nobody users 20480 Aug 13 00:14 ../
-rw-r----- 1 nobody users  4643 Dec  3  2018 ansible_ad-hoc_commands.txt
-rw-r----- 1 nobody users   619 Dec 10  2018 ansible_vault.yaml
-rw-r----- 1 nobody users   879 Dec  4  2018 ios_command_behavioral_inventory_parameters1.yaml
-rw-r----- 1 nobody users   754 Dec  4  2018 ios_command_local_with_vars_and_provider.yaml
-rw-r----- 1 nobody users   763 Dec  4  2018 ios_command_network_cli_privileges.yaml
-rw-r----- 1 nobody users   781 Dec  3  2018 ios_command_save_to_file.yaml
-rw-r----- 1 nobody users   264 Dec  4  2018 ios_config_backup.yaml
-rw-r----- 1 nobody users   505 Dec  4  2018 ios_config_parents.yaml
-rw-r----- 1 nobody users   548 Dec  7  2018 linux_loops.yaml
-rw-r----- 1 nobody users   492 Dec  7  2018 linux_loops1.yaml
-rw-r----- 1 nobody users   449 Dec  7  2018 linux_loops2.yaml
```
i'll fix this and report back, this could be the root cause

**Comment by 9001** [comment]
> tags im assuming in this instance refers to music metadata?)

yup! and also multimedia information in general, so stuff like video resolution, bitrate, etc.

in the config, you're setting `hist=/db` and I'm guessing that is a docker volume pointing to `/mnt/dkr/appdata/cpp/db`, so that should be fine. My first theory was that `/db` was not mapped anywhere, so it would disappear on each reboot, but that's apparently not the case...

> `-rw-r--r-- 1 administrator 1000 3304734720 Nov 11 15:17 up2k.db`

...in fact, it is HUGE! on a server with few tags it'll take about 512 bytes per file, meaning you should have around 6 million files in that volume. Is that correct?

> could it be related to the e2ts and the absense of tags?

e2dsa + e2ts is a good combination; it will scan for new files on startup (e2dsa) and then, for each new file, check for tags (e2ts). If the file is found to not have any tags, it will remember that and not try again. So this shouldn't be causing rescand on each startup.

One thing I should clarify is that it's normal to see all of the filenames flash by during startup -- that's not because it is reindexing; it is just verifying that all of the files that was indexed earlier are still there. And if you do have as many as 6 million files, then I suppose that would take a little while.

There is an optimization ('dhash") to speed this up, which is default-enabled, which performs a much faster verification. This optimization disengages if a database desync is suspected; in that case, it will do a more detailed check, but only during the next startup. One way for this to happen is if you shutdown copyparty while it is still verifying the index (including checking for tags). In that particular case, there is a warning in the log that the next startup will take a bit longer:

`dropping caches for a full filesystem scan`

even with the dhash optimization engaged, it will still take a look through all of your folders, so your HDD might bottleneck startups a tiny bit.

> also whats a little frustrating about this too is that theres no graceful stopping of the container in both docker compose and docker whilst the db scan is running

it should always safe to send a CTRL-C or a SIGINT/SIGTERM, or rather, assuming you still get all of the usual "ok bye" and "nailed it" during shutdown. And even if you don't, the underlying database library (SQLite) is hella robust and can take a beating for sure. But if you do find that you're not seeing the regular shutdown messages, then I'd like to know more about your setup so I can try to reproduce it, just out of curiosity.

**Comment by mrpops2ko** [comment]
```
19:55:05.411 hsrv                  ok byeient/node_modules/debug/src $
19:55:05.411 tcpsrv                ok bye
19:55:05.411 up2k                  writing snapshot
```

looks like im getting the messages, and i've gone through and fixed the perm issues

yeah the total amount of files looks correct, maybe even more lol - i have a lot of very small files

some of which have very long paths (which i suspected as a possible issue) 

but lets see how things go now, i did notice it was as you mentioned about the indexing in that it doesn't do a full proper scan of the files - it wasn't hash checking the files, just checking their filesize or some other data
