### ISSUE TITLE
PKGBUILD improvements

### ISSUE THREAD

**Issue by icxes** [9001/copyparty#17]
Starting this so I don't forget

- [x] ~~better pkgver() (first try didn't work so good, second try doesn't actually have the version, just the commit id)~~ manual/automatic-on-release pkgver
- [x] ~~the build process might be improved, looks a bit sus currently (still works tho) ("[grab the web-dependencies](https://github.com/9001/copyparty/blob/hovudstraum/docs/devnotes.md#building=)" had some problems so didn't include it yet)~~ just download the latest sfx instead of building
- [x] the config include thing mentioned in #15 
- [ ] add to AUR so I don't have to manually update (maybe when the PKGBUILD is good enough)
- [x] note what functionality optional deps are needed for
- [x] ~~separate PKGBUILDs for release and git versions~~ just release should be fine
- [ ] ???

**Comment by 9001** [comment]
come to think of it, how from-scratch do we want the package to be? it's probably fine to just download the sfx to /usr/bin and run that every time really, would be the easiest and most future-proof / least-maintenance approach, and wouldn't have to worry about deps at all -- except it carries a tiny startup cost as it extracts stuff into /tmp

the next best thing might be to base it on packages from pypi rather than the sfx (since both of them include all of the web-deps), and that way you'd get a super-fresh copy of jinja2 instead of the sfx-bundled version (which is perfectly safe but maybe not as fast), not sure how to actually install those onto the filesystem tho, should look at [the jinja2 pkg](https://github.com/archlinux/svntogit-community/blob/packages/python-jinja/trunk/PKGBUILD) or other python pkgs for reference (altho my setup.py might cause issues being hella jank)

would be "easy" to do git builds that way too, clone the repo, put the deps in place [like you mentioned](https://github.com/9001/copyparty/blob/hovudstraum/docs/devnotes.md#building) except make the package using setup.py instead of make-sfx (if that even works on its own)

could also go all the way and build all of the deps from scratch with [the deps makefile](https://github.com/9001/copyparty/tree/hovudstraum/scripts/deps-docker) except that would definitely be overkill...i think

and regarding optional deps, i'd say to completely forget about smb / impacket since those are a certified bad idea w

**Comment by 9001** [comment]
just some ideas for later, not actual questions! and thx btw :>

**Comment by icxes** [comment]
the easiest way would probably indeed be just to get the https://github.com/9001/copyparty/releases/download/${pkgver}/copyparty-sfx.py, and it's how i'd do it if it didn't mean i'd have to check whenever there's a new release available and update the PKGBUILD (could automate this easily enough i guess)

as for the packages, idk about that stuff but whatever's good as long as it doesn't install stuff in the filesystem outside the project directory (or whatever is explicitly listed in the PKGBUILD)

as for the optional deps, kinda have to put everything there for package management reasons in cae someone actually wanted to use that stuff

**Comment by 9001** [comment]
I'm not familiar with how pacman/yay/etc works so I don't have any specific ideas on that part :p but I guess it wouldn't be enough to use the [latest version url](https://github.com/9001/copyparty/releases/latest/download/copyparty-sfx.py) since pacman relies on the pkgver to know if there's an update(?), and that would only get bumped if a new PKGBUILD is pushed right?

and yeah forget about the setup.py and all that, not worth it -- and the sfx will ignore the bundled libraries if it finds a systemwide installation anyways, so just listing `python-jinja` as a mandatory dependency should be enough to cover the only issue i can really think of in that regard

some people might dislike the sfx unpacking stuff into /tmp and running from there but ehh let's see what they say :>

**Comment by icxes** [comment]
so the correct way to do this would be to manually check the package version and update it in pkgver, then update the checksums as well as make sure it actually builds, then push the updated PKGBUILD to AUR. if you have some script you use for releases, you might be able to automate that on your side easy enough (just sed new version to pkgver and checksum to sha256sums), then i can just have push notifications for new releases and grab the auto-updated PKGBUILD and update the AUR package (when i get around to putting it there eventually)

either way i'll look at changing it from a -git version to a release version first, maybe hit you up to see about what's necessary and what isn't with the deps and stuff

**Comment by 9001** [comment]
sure thing, 99% of the release process is scripted so updating the checksums + committing the new PKGBUILD to the repo before the release goes live shouldn't be a problem, I can start doing that :+1:
