### ISSUE TITLE
Folders being deleted unexpectedly

### ISSUE THREAD

**Issue by seanmcveigh** [9001/copyparty#23]
Hi, Nice little project! Just testing it out and noticed some oddities regarding folders that may be design intent, but thought I'd inquire :)

1. when deleting the only file in a folder, the folder is also deleted. this leaves the UI with a spinning christmas tree and the message "could not list files in folder: error 404: file not found".  refreshing the UI shows that the folder has been deleted.  up2k log indicates "deleted 1 files (and 1/1 folders)".  Perhaps this is expected behaviour, and there is a config option to disable this pruning? 
2. when moving an empty folder, the folder is deleted. perhaps a similar cause as above.  I came across this after creating 2 folders in a row: dir1 and then dir2.  This created /dir1/dir2, which I wasn't expecting, so I tried moving /dir1/dir2 to /dir2, so I would have 2 folders at the top level of the root.  Both folders ended up deleted.  I also tried the opposite - creating /dir1 and /dir2 and then tried moving /dir2 into /dir1.  I was left with only /dir1 (dir2 was deleted).
3. renaming an empty folder causes it to be deleted.  similar pruning to above is happening it seems.  create /dir1.  rename /dir1 to /dir2 - it disappears :)

Anyhow. Thanks for your time!

version info:
running on ubuntu 18.04 LTS
copyparty v1.6.15 "cors k" (2023-04-26)
  CPython v3.6.9 on Linux64  [GCC 8.4.0]
   sqlite v3.22.0*1 | jinja2 v3.0.3 | pyftpd v(None)

**Comment by 9001** [comment]
Hey there, thanks for dropping by :>

Right now this is "intended behavior" but just because it was easier to code that way -- it only cares about getting the files into the right place, and then deletes whatever folders are left over :p

But yes, I agree this is confusing / unintuitive, especially in cases like the ones you mentioned... So I'll get something done by the next version :+1:
