### ISSUE TITLE
cannot specify username at login screen

### ISSUE THREAD

**Issue by seanmcveigh** [9001/copyparty#25]
Hi again.. thanks for the quick fixes for the other issues I raised :)

If I launch with:
`copyparty -a user1:pass -a user2:pass`
I was expecting it to allow 2 users, but entering "user1" or "user2" on the login screen logs "invalid password: user1".
If I enter only "pass", it logs me in as user2.  It seems the "act" input is hidden by default. (as a suggestion, accepting only a password is a bit less secure, but seems to be design intent. not that I have more than one user :)
I haven't tried setting up a config file yet, since I'm just experimenting, but perhaps that un-hides the "act" field on the login page?

**Comment by 9001** [comment]
Hey o/
no prob! and thanks for the fresh input, appreciate it :>

the reason it's only asking for a password is to minimize the amount of user interaction required (between phones in a rush for instance), and I figured you could make a longer password to compensate in other scenarios... but this whole thing assumes everyone will have unique passwords, which is obviously not the case as you've shown :p

so the fact that you were able to add two accounts with the same password is unfortunate -- should definitely have been detected as an error during startup. So if nothing else I'll at least get that fixed :>

I guess the bad news is it'll be tricky to start asking for a username during login at this point, since it's an assumption that's spread all over the code + into clients too... Maybe it would be acceptable to get around the issue by making the passwords themselves `username,password` or something, just as a convention? so `-a user1:user1,pass` for example

(in case you decide to go with that approach, I'd advise against using the `:` character as a separator, just on a hunch that some FTP clients or whatnot will be confused...)

and regarding the "act" field -- that's the action handler to invoke on the server, hence the hardcoded value "login" -- so that's also why it's hidden ;)

**Comment by seanmcveigh** [comment]
ah that makes sense.. I thought maybe "act" was shorthand for account :)
ok, knowing this, I will proceed with configuring safely.  so it's a password->user map.  again, I'm probably only using one user :)

**Comment by 9001** [comment]
as a followup to this, as mentioned in #680 it is now possible to enable usernames as an optional feature
