### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: b'/.hist'

### ISSUE THREAD

**Issue by burningscript** [9001/copyparty#27]
-

**Comment by 9001** [comment]
Sure! Yeah this definitely sounds like it is permissions-related somehow.

I'm curious how you are running copyparty; are you perhaps using docker or podman? And, if you are using podman: Are you root or a regular user when you run the command to start the container?

Also, what Linux distribution / version are you using? This might be relevant because some distros have SELinux which can cause very similar issues.

**Comment by burningscript** [comment]
I installed it on my Raspberry Pi completly without docker. But I was able to make it work by adding "--hist" with a different folder on my storage device to it. Now the thumbnails are working fine :)

Maybe you can help me with something else: Is there a "default" admin password? I am using copyparty for myself, but I am not familiar with your account system and I just want to rename / delete files :)

**Comment by 9001** [comment]
Glad to hear :> it is possible the initial error message was a bit misleading; it was trying to make the `.hist` folder inside the same folder you were running copyparty in. The public error messages which appear in the browser don't include the full filesystem paths due to security reasons, so it probably looked like it was talking about the root of the SD card instead. I'll see if I can make that more obvious 👍 

The only default account is the guest account (with no password) which gets read-write in the folder where you launched copyparty. The recommended way to specify accounts and permissions is by making a config file -- but if you just want to give everyone read-write-move-delete instead, you could do the following: `-v .::rwmd`

Or, if you want to give everyone else read-access, and create an admin account with full access for yourself: `-a admin:yourpwd -v .::r:rwmd,admin`

There's more information in the [accounts and volumes](https://github.com/9001/copyparty#accounts-and-volumes) section of the readme, which hopefully manages to explain the arcane syntax as well ;)

**Comment by burningscript** [comment]
Thank you very much and keep up the good work :)
