### ISSUE TITLE
Option to disable media player and default to download

### ISSUE THREAD

**Issue by ncflagg** [9001/copyparty#28]
I have a use case where the client app (DeoVR) needs to have the video file (I.E mp4) streamed directly in order to function. Is there a way to disable the media player globally or per-folder? I would still want to retain thumbnail function in gridview.

**Comment by 9001** [comment]
Hey there!

You're right, this is currently not possible out of the box... But we can get around that by adding a bit of custom js :>

This should hopefully do what you had in mind:

```javascript
// disable the gallery initializer
thegrid.bagit = noop;

// and terminate any existing gallery instances
try { baguetteBox.destroy(); } catch (ex) {}
```

try putting that into a file which is accessible by all clients, for example `.custom.js` right inside the webroot, and then enable it with the commandline args `--js-browser /.custom.js`

**Comment by ncflagg** [comment]
I'm running in a docker container. I tried adding `--js-browser /.custom.js` to my docker command but it doesn't like it.

**Comment by 9001** [comment]
Oh, then I guess you're using config files instead of commandline args (good!) -- if that is the case, try adding this config section to the top of your config file instead:

```yaml
[global]
  js-browser: /.custom.js
```

if that doesn't work either (or if you're not using config files at all), then it's time to debug a bit -- the first thing to check is if the config is taking effect at all. So in that case, could you navigate to a folder in copyparty, hit F5 to refresh, and CTRL-U to show the html source? If the config works, there should now be a `<script src="/.config.js?...` near the end

**Comment by ncflagg** [comment]
I wasn't using a custom.conf, but I am now! That works. Thank you very much.

Can I use a similar method to hide files with a particular extension?

**Comment by 9001** [comment]
You have a lot of good ideas :-)

Filtering by file extension sounds cool, so that'll be possible in the next version, maybe in a few weeks -- unfortunately that one's a bit harder to pull off on the client-side, so while it's *technically* possible to hack it... it's be better to wait hehe

Glad to hear the fix worked tho!
