### ISSUE TITLE
Full, uncropped thumbnails

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#43]
Currently, the generated thumbnails are square, and unfortunately this also cuts-off a lot of images. You can see this in the repo's own image example, where e.g. the text "Internet!" on the bottom left picture is cut off, because the image is "too tall". 

![image](https://github.com/9001/copyparty/assets/21365711/4a4509b3-71e4-4822-b94e-8e8f72532b2d)

I've tried fiddling with the css but then realized the generated thumbnails were just square. This is a bit inconvenient when browsing photos I've taken on my phone, since a lot of those tend to be in portrait. If I'm browsing e.g. mirror selfies, the crop will cut off at my face/show mainly my chest, which is less than ideal.

I'd like an option to generate the thumbnails without cropping, ones which show whole image, even if it doesn't neatly fit into the square, like e.g. Windows Explorer does:

![image](https://github.com/9001/copyparty/assets/21365711/78429766-5f4d-4485-b895-c68cf4c2da62)

Thumbnails are generated using third-party libs, but I do not know how copyparty uses them. If I'm supposed to add a config file for them instead or something I'm happy to do that, though I would appreciate some directions. 

If it's up to copyparty to do this though, then I think it should provide a config flag that toggles what type of thumbnail to generate (crop to center vs fit). `pyvips`, for example, has a `crop` parameter which you can adjust. I personally think it's generally ok if e.g. it only works on `pyvips`, but perhaps ffmpeg/pillow also have such settings.

(I have `pyvips` installed, but I cannot actually tell what copyparty is using? Is there a config setting I'm expected to specify, or will it just always prefer pyvips over ffmpeg even if it finds both?)

**Comment by 9001** [comment]
hey o/

I believe the `--th-no-crop` option does what you want, so please give that a try if you haven't :>

if that doesn't work, it could be due to one of the following:
* `pillow` is really old
* there are cached thumbnails from before `--th-no-crop` was enabled

installing `pyvips` would get around the pillow issue, and clearing the thumbnail cache can be done by deleting the `th` folder inside the volume's `.hist` folder.

btw, apparently the no-crop option is currently only available as a global option -- it would be nice if it was available as a volflag as well, so I'll fix that!

regarding which library is currently in use for thumbnailing, this should get printed on startup:
```
18:39:38.525 thumb      decoder preference: pil, ff
```
...meaning that it'll try pillow first, and then fallback to ffmpeg if that fails, as I don't have pyvips installed currently.

All of these facts should definitely be better documented, so I'll see what I can do about that... always the hardest part :-p

Let me know how it goes!

**Comment by Gremious** [comment]
> I believe the --th-no-crop option does what you want, so please give that a try if you haven't :>

Oh that's brilliant, thank you! Yeah I don't think there's a mention of it in the readme (?), so please consider adding it in the thumbnails section or so

Other than that - it worked perfectly as expected c:

Some notes for future people potentially reading this issue:
1. The `.hist` folder is at the root of the copyparty volume, not in the actual subfolder with your pictures (makes perfect sense, but I had to take a second to realize that).
2. Remember to refresh the browser cache for the page also cause it'll still re-use those thumbnails (hard-reloading works just fine)
