### ISSUE TITLE
Hitting 404 rate limit when transfering large amount of files with WebDAV using GVFS

### ISSUE THREAD

**Issue by nanawel** [9001/copyparty#55]
**Describe the bug**
When transfering a large amount of files with WebDAV (and possibly because how [GVFS](https://wiki.gnome.org/Projects/gvfs) handles that) it's really easy to hit the 404 rate limit and have its IP get banned for 24h.

**To Reproduce**
Transfer a large amount of files, and you should see a log similar to the following in copyparty:

```
PFIND {path to file 1}
Not Found {path to file 1}
PFIND {path to file 1}
Not Found {path to file 1}
PUT {path to file 1}
<size of file 1>

PFIND {path to file 2}
Not Found {path to file 2}
PFIND {path to file 2}
Not Found {path to file 2}
PUT {path to file 2}
<size of file 2>

(repeating for each subsequent file)
```

You can see that the client here tries to check if the file it's about to transfer does not already exist (which is a safe way to do, imho), but it means that each PFIND that queries a nonexistent file will get a 404, and copyparty will record that as a brute force attempt.

**Expected behavior**
There's no perfect way to handle that, but maybe one workaround would be to "cancel" the recorded 404 generated by the PFIND for the client if it transfers a file at the same location immediately after.
This way it should be possible to transfer a huge amount of files without risking to hit the rate limit for wrong reasons.

**Comment by 9001** [comment]
Thanks! This probably affects windows as well.

I wonder if the best solution would be to disable the 404-check for users which are able to see the directory listing regardless; the current behavior doesn't make a lot of sense in hindsight. In other words, if you have anything other than the `g`, `G` or `h` account permissions, then 404's are entirely allowed (including if your account is write-only).

This would disable the current benefit of automatically banning malicious crawlers spamming the server with requests for common vulnerabilities, but aside from the increased cpu load there's not much harm in those, so that is probably fine.

I'll mull this over today -- let me know if you think there's something I've missed so far :>

**Comment by nanawel** [comment]
Wooah, blazing fast :smiley: 

Yes, your solution seems even better. :+1: 

Btw, while trying to deal with the ban policy on my instance, I couldn't find a way to raise the limit using my config file. Could you tell me what the problem could be please?

I'm using this file (which is correctly loaded, I checked):
```
[global]
  name: myhost.tld
  theme: 1
  # Trusted proxy (Docker)
  xff-src: 172.
  # Logging
  lo: /log/cpp-%Y-%m%d-%H%M%S.txt.xz
  ban-404: 9999,60,180
```

Here the `ban-404` does not seem to be taken into account because when I hit the limit the log still says that the IP is banned for **24h**, so that's a pretty simple deduction.
Of course I restart the container entirely after each modification.

**Comment by 9001** [comment]
😁👍 
How strange though, that should have been fine... Is that your entire config, or are you perhaps running copyparty with either `-ss` or `-sss` as well? I think `-ss` and `-sss` would override your value for ban-404 (which they really shouldn't, so I'll fix that as well 👍)

**Comment by nanawel** [comment]
> perhaps running copyparty with either `-ss` or` -sss` as well? 

Nope, this is my whole config for `[global]` unfortunately.
I use the `copyparty/ac` Docker image which means the only flags used are  `--no-crt` and `-c /z/initcfg`:

```
PID   USER     TIME  COMMAND
    1 1000     23:12 python3 /z/copyparty-sfx.py --no-crt -c /z/initcfg
```

> which they really shouldn't

This was my understanding too :wink: 

Thanks very much!

**Comment by 9001** [comment]
Hmm okay, I still can't see any reason that `--ban-404` would get enabled with your setup. But there's the other triggers, which all happen to have the same ban duration, namely `--ban-403`, `--ban-422`, and `--ban-url`.  Out of those three, I think you might be hitting the last one.

so, the next question! is there perhaps some .php files amongst the files you're uploading? or anything wordpress-related? This probably sounds hella weird, so let me explain :p

`--sus-urls` is a list of URL patterns (used by `--ban-url`) which are candidates for triggering a ban on 404, for scenarios where enabling `--ban-404` would be too risky. The default pattern was intended to catch the most common malicious web-crawlers, just to reduce the cpu load that they would cause. Didn't stop and consider that somebody might want to upload such files over webdav 😅  So since this feature doesn't really help all that much in the first place, might as well just get rid of it i think.

but just to make sure we got it right, could you grep the log for the first `client banned:` message? and maybe `grep -C10` for 10 lines of context, so we can see what URL caused it? that should tell us which of the triggers you got hit by :>

**Comment by nanawel** [comment]
> so, the next question! is there perhaps some .php files amongst the files you're uploading? or anything wordpress-related? 

You're perfectly right, I was archiving some old projects so I had a bunch of PHP, XML, JS, and other source code files in them (including GIT and SVN metadata). They probably are good candidates for this blacklist!

> but just to make sure we got it right, could you grep the log for the first client banned: message? and maybe grep -C10 for 10 lines of context, so we can see what URL caused it? that should tell us which of the triggers you got hit by :>

Ah damn, I've lost the history and worked around this by creating ZIP archives instead of having a bunch of small files. Sorry :confused: 

I was also thinking of another "small" feature: **IP whitelisting**.
I understand that from the big scary Internet there should be some hardened security measures and limitations. But it would be handy to say "oh from the LAN, don't be too picky and work at max speed, it's safe". Some key that would allow a list of (partial) addresses so that `-s` and the others won't apply. Of course it means dealing with `X-Forwarded-For` when running behind a reverse-proxy :confounded:

**Comment by 9001** [comment]
> bunch of PHP, XML, JS, and other source code files in them 

awesome, that was definitely it then :> thanks for your help figuring this out!

> Some key that would allow a list of (partial) addresses so that -s and the others won't apply.

hey that's a cool idea, I'll see if there's any ratelimits or such which would benefit from something like that.

I'll post a new version this Sunday probably 👍
