### ISSUE TITLE
Versionned docker images

### ISSUE THREAD

**Issue by Thibugs** [9001/copyparty#58]
Hello, first of all, thanks for this amazing tool 😄 

As of right now, the only docker images available are tagged with "latest", there is no version tagged images (For example ghcr.io/9001/copyparty-im:v1.9.15 / ghcr.io/9001/copyparty-im:1.9.15).

On Docker alone, it's not much of an issue as you can just pull the image and get the update, but on Kubernetes (What I use), I have to either add or remove the "latest" tag from the deployment to force a rollout of the update.

I know that Kubernetes is not a supported use case, but having version tagged  images would probably make some users more comfortable, as some people don't like to use the "latest" tag and prefer to stay on a specific version instead of being on the edge.

**Comment by 9001** [comment]
Hey! Thanks for using copyparty, and thanks a lot for the input -- really appreciate it :> I'm still fairly new to everything docker and containers so I don't really know what I'm doing hehe

I'll get this fixed by the next version 👍 and let me know if you can think of anything else that would improve the experience too :>

**Comment by kkovaletp** [comment]
> I'm still fairly new to everything docker and containers so I don't really know what I'm doing hehe

well, in that case, I'd also recommend you adding the next useful tools in your docker build and publish pipeline:
- [dockle](https://github.com/goodwithtech/dockle)
- [Hadolint](https://github.com/hadolint/hadolint)
- [Dive](https://github.com/wagoodman/dive)
- Anchore's [Syft](https://github.com/anchore/syft) and [Grype](https://github.com/anchore/grype)

They will let you control the quality of the images and quickly fix or overcome known vulnerabilities.

Also, I'd recommend including the Anchore's tools in the code testing pipeline in order to better detect and scan the code dependencies.
