### ISSUE TITLE
Show hidden files button does not show hidden files

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#66]
Made a new folder called `.dotfolder` using the copyparty make a directory button, it made it fine and moved me into it. 
I also made a `.dotmd.md` file.

Going back a page and refreshing hides it, as expected. But toggling the `dotfiles` setting on/off doesn't reveal any of the hidden files/folders.

The button does say "show hidden files (if server permits)" and I guess server does not permit - but I couldn't really find anything abt that in the readme. Do you happen to know what I need to change to allow it to show hidden files? Is there a volflag or something?

The permissions look like this, everyone _should_ have at least read permissions.

```
gremious@hostname ~/snip/public> eza -la
drwxr-xr-x   - gremious  9 Dec 19:27 .dotfolder
.rw-r--r--  10 gremious  9 Dec 19:30 .dotmd
drwxr-xr-x   - gremious  3 Dec 20:39 .hist
drwxr-xr-x   - gremious  8 Dec 12:55 Misc
.rw-r--r-- 214 gremious  8 Jul 15:51 README.md
.rw-r--r-- 193 gremious 12 Jul 20:25 test.html
```

**Comment by 9001** [comment]
ah yeah, that is the `-ed` global setting (enable dotfiles) -- and looks like that is only documented in `--help` so that's a bit unfortunate...

currently it's not available as a volflag, which would have made sense in retrospect, so I'll add that at some point :+1: 

keep in mind that `-ed` makes it possible for everyone to see dotfiles, assuming they have read-access to the folder! not sure if it would make sense to make that more granular, I kinda think we have enough permission types already heh

EDIT: hmm, maybe there could be a volflag where you can specify a list of usernames which are allowed to see dotfiles

**Comment by Gremious** [comment]
Thank you very much!

---

> so I'll add that at some point 👍

Very cool, appreciated 🙏 

> hmm, maybe there could be a volflag where you can specify a list of usernames which are allowed to see dotfiles

If it's not to much work - I'd love to have that!
