### ISSUE TITLE
Uncaught ReferenceError: EasyMDE is not defined

### ISSUE THREAD

**Issue by thaddeuskkr** [9001/copyparty#73]
was trying the fancy editor for the first time, got this (this is the latest docker pull i think)

![image](https://github.com/9001/copyparty/assets/49682825/c3bc8c9d-7c51-4f14-9b6b-7f0d8cb2590b)

**Comment by 9001** [comment]
Hmm... The fancy editor is unique in that it tries to save some space by using brotli-compression for its js and css. Copyparty is not able to decompress brotli, so the browser won't be able to load the resources if the browser (or proxy) didn't include `br` in the list of accepted transfer compressions. So I'm guessing it's the reverse-proxy that expects all responses from copyparty to be uncompressed.

Since I'm fairly certain this is the issue, I've pushed new docker images which uses gzip compression instead. Hope this fixes it :>

Out of curiosity, what reverse-proxy are you using?

**Comment by thaddeuskkr** [comment]
> Out of curiosity, what reverse-proxy are you using?

Oops. Forgot about this - I'm using Caddy. And yeah, the new Docker image works
