### ISSUE TITLE
No FTP folders

### ISSUE THREAD

**Issue by Derweis** [9001/copyparty#76]
NOTE:
all of the below are optional, consider them as inspiration, delete and rewrite at will, thx md

**Describe the bug**
FTP is uncommented, the port has not changed, it does not load folders when trying to log in to the server

**Server details**
if the issue is possibly on the server-side, then mention some of the following:
* server OS / version: debian 12
* python version: 3.11.2
* copyparty arguments: 
* filesystem (`lsblk -f` on linux): ext4

**Client details**
if the issue is possibly on the client-side, then mention some of the following:
* the device type and model: 
* OS version: 
* browser version: filezilla

**Comment by Derweis** [comment]
![image](https://github.com/9001/copyparty/assets/15996927/410be8f1-fae3-4dca-a09f-2cb7ee5375bb)
![image2](https://github.com/9001/copyparty/assets/15996927/58d0d296-75d4-4de8-8cc3-536928cc9c81)

**Comment by Derweis** [comment]
![image3](https://github.com/9001/copyparty/assets/15996927/bc96c851-ec32-470b-8242-83aff466d734)

**Comment by 9001** [comment]
Hello, and thanks for giving copyparty a try :+1:

I think you're getting this issue because you're running copyparty in docker, which gets a bit tricky because FTP is a weird protocol... it uses the main socket (on port 3921) just for sending control messages back and forth, but it will open an additional connection for larger stuff (each directory listing, and each file transfer). And there's a difference between active and passive mode, which decides if the client will make another connection to the server, or if the client should start listening for a connection from the client... So this makes FTP a bit slow, and a pain in the ass to deal with :grin: 

You'll want to specify a port-range to allow copyparty to use for data transfers, for example 12000 through 12099, which will allow for 100 actions in parallel. And you will have to tell copyparty what the server's external IP is, which is the only IP that the clients will be able to connect to, since docker kinda destroys that information by routing the connections through its own network before it hits copyparty.

The following additions to the `[general]` config section should tell copyparty what it needs to know:

```yaml
[global]
  ftp-nat: 127.0.0.1
  ftp-pr: 12000-12099
```

Replace `127.0.0.1` with the actual IP that the clients will be connecting to, or leave it as 127.0.0.1 if you'll only be using this yourself.

Then, finally, you need to run the docker container with all the ports from 12000 through 12099 forwarded to ports 12000 through 12099.

Let me know if it works out! And thanks for pointing this out, I'll see if I can mention it somewhere in the docker documentation :+1:

**Comment by Derweis** [comment]
Thank you very much, it helped
