### ISSUE TITLE
copyparty.service configuration issue?

### ISSUE THREAD

**Issue by c0de517e** [9001/copyparty#88]
Not sure if this is an issue or I'm just too n00b, but I added copyparty to my home server raspberry pi and following the instructions in the contrib/copyparty.service I got something working, but thumbnails would not generate/display correctly.

In the end I managed to make it work by changing RestrictSUIDSGID=true to false, as I noticed in the logs the service was failing to create the directories for the thumbnail database, but otherwise it add access to the files just fine, including uploading new ones and deleting ones from the web interface.

The directory I was using for copyparty was /mnt/SSD which maps to an usb SSD drive I have attached to the pi, ext4. It is not created/owned by the copyparty user/group, but it gives every user all permissions (777) so I imagine that was not the issue.

Lastly, minor, the instructions in copyparty.service do not mention to create the /var/lib/copyparty directory but I figured that was needed too.

**Comment by 9001** [comment]
Hey, and thanks for using copyparty 😁 👍 

This is a bit of a headscratcher, so I'd like to try reproducing it -- what linux distribution (and version) are you running on the pi? Mainly asking because some distros have stuff like selinux and apparmor which tends to cause issues like this.

Glad to hear you got it working tho :>

**Comment by c0de517e** [comment]
Just vanilla raspbian, latest version, nothing fancy.

pi@raspberrypi:/mnt $ hostnamectl
   Static hostname: raspberrypi
         Icon name: computer
        Machine ID: 52017452719d45a0b35a2289c16c5958
           Boot ID: b11417b2862b411c8ac00de69c7c6e5c
  Operating System: Raspbian GNU/Linux 11 (bullseye)
            Kernel: Linux 6.1.54-v7+
      Architecture: arm

It's so unfancy I never even added an user other than the default "pi". These are the permissions of my /mnt/SSD
 drwxrwxrwx  5 pi   pi   4096 Jun 23 21:10 SSD

And this is how I set that up in fstab:
PARTUUID=1375cf2e-a9d8-475f-b282-6712bcfb5640 /mnt/SSD ext4 defaults,noatime,nofail,nodiratime 0 1

copyparty.conf and .service are basically the ones in /contrib, untouched, just changed /mnt to /mnt/SSD in .config, added an user/password, and then I followed all the instructions in the .service, but as mentioned I needed to create by hand /var/lib/copyparty and then I needed to change that RestrictSUIDSGID otherwise I could see in the log that the creation of the .hist/... directory structure for the thumbnails was failing.

Anyhow. Maybe it's just easy to add a note in the .service instructions that if people are encountering issues with thumbnails, they can try changing that RestrictSUIDSGID=true to false and see if it helps...

And thanks for making this! I previously was looking at owncloud and nextcloud, but they seemed to complex and heavy to bother. I ended up settling with ftp and samba which was easy enough, but not ideal, neither mac nor windows support ftp well out of the box and samba is terrible over the internet.

copyparty is a breath of fresh air, I wish I found it earlier!

**Comment by 9001** [comment]
alright, so let's start with the easy part -- `/var/lib/copyparty` should have gotten created automatically, and I assumed `useradd` would do that, but turns out it doesn't unless you also specify `-m`... D'oh!

but the really confusing part is why `RestrictSUIDSGID=true` would affect thumbnails; I've been racking my brain and can't think of a reason it would be related at all. But it's a good idea to add a hint that the hardening could cause some unanticipated behavior, so I followed your suggestion on that :>

> copyparty is a breath of fresh air, I wish I found it earlier!

haha thanks 😁 awesome to hear you're finding it useful!

do let me know if you hit any more issues 👍 👍
