### ISSUE TITLE
Inconsequential questions about mounting

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#90]
The rclone example command copyparty shows sets `vendor=owncloud`... any particular reason why? I don't think copyparty has anything to do with owncloud? They do have a WebDAV vendor which feels more accurate.

It also mentions that "rclone is much slower" than webdaw/davfs2 - is this true? I would have though rclone would be way faster, using a newer protocol and all? At least [one random dude out there](https://gist.github.com/joshtrichards/e245aa5cd402b8c0c485a3945ba3ce77) benchmarked it to be faster than davfs2, but idk if that's true for copyparty specifically?

**Comment by 9001** [comment]
the main reason for `vendor=owncloud` is so it enables `useOCMtime` in rclone, so files will retain their lastmodified timestamps after uploading, although `canChunk` might have been a cool feature to enable as well, to improve cloudflare support... would require some work on the server, so I'll make a note of that :>

as for the remark on the services page saying "you can use rclone instead, which is much slower", this is probably still true when  you're transferring many small files (because davfs2 has the benefit of skipping some userspace/kernel round-trips), but rclone performance improved A LOT when it became possible to specify `pacer_min_sleep=0.01ms` in the rclone configs, so this may need to be benchmarked again, thx for the heads-up!

also that comparison doc is cool, think I'll spin off that and try some more combinations :+1:

**Comment by Gremious** [comment]
Thank you!

**Comment by 9001** [comment]
well, we can scrap the davfs2 recommendation -- rclone beats it out of the water, especially when there's a bit of latency. This is assuming you're on rclone v1.63 or later and using the `pacer_min_sleep=0.01ms` rclone option; if that's not the case, then you're back in the timeframe from when the docs were written and davfs2 was still the best choice heh

I'll update the docs when I have some more actual numbers, but it's looking like rclone being up to about twice as fast :>

EDIT: oh and rclone's webdav is WAY faster than ftp for small files (not surprising, given how crazy the ftp protocol is) -- ftp has a tiny advantage for big files, but it's not likely to apply in reality, so webdav's the way to go
