### ISSUE TITLE
davfs2 password ignored unless I mount the protected folder directly

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#91]
**Describe the bug**
I don't know if this is a limitation of webdav/davfs2, or if copyparty can do something about it.

I try to mount copyparty via webdav/davfs2.

I am on EndeavourOS (Arch-based).

If I `mount -t davfs -ouid=1000 https://mydomain.com/ /mnt/test` and put in the username/password, it does mount, but I can't see any user/password protected folders, only public files.

Only if i `mount -t davfs -ouid=1000 https://mydomain.com/private/dir/ /mnt/test` does it actually show that directory.

I don't believe adding that specific directory with a password to my `secrets` file works.

The `daw` flag is set but only for that one private directory.

Is there anything that can be done about that?

**Server details**
```
[SFX]    this is: copyparty 1.13.0
[SFX]  packed at: 2024-04-20, 22:41:59 UTC, 1713652919
[SFX] archive is: /usr/local/bin/copyparty-sfx.py
[SFX] python bin: /usr/bin/python3
[SFX] python ver: CPython 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

[SFX] found early
[SFX] jinja2: bundled
[SFX] pyftpd: bundled
[SFX] sfxdir: /tmp/pe-copyparty.1000.817.0
```

**Comment by 9001** [comment]
Yeah, I've been trying to find a good workaround for this as well... The issue is that davfs2 initially tries to connect without a password, and then it decides to skip authenticating entirely since it got some files in return. And I think the builtin client in windows does something similar.

The best suggestion I've got is to enable `--dav-auth` which rejects all webdav connections unless they actually authenticate. Depending on your usecase this might be perfectly fine -- or rather, assuming everyone who's connecting to your server has an account.

If that's not the case, I'll see if I can come up with some other workarounds :>

**Comment by Gremious** [comment]
Thank youu, for me `dav-auth` is enough, I just want to mount it on my own system, and anyone else potentially mounting it would be a friend (user) anyway :)

This seems to work perfect now, I appreciate it!
